### ISSUE TITLE
转发TCP给$$tap加速无效并夸张占用

### ISSUE THREAD

**Issue by Cathgao** [wangyu-/tinyPortMapper#5]
用tinyportmapper转发远程服务器的端口给$$tap配合udp2raw加速游戏。但tinyportmapper转发tcp后让$$tap链接会出现tPM大量连接刷屏并造成CPU100%占用，而且网络全断。
所用命令为`tinymapper.exe -l0.0.0.0:3333 -r****:37371 -t` ****为服务器地址
![default](https://user-images.githubusercontent.com/21031564/41996135-8865c37c-7a86-11e8-81d3-083289921b48.PNG)

**Comment by wangyu-** [comment]
这个我也遇到过，可能是sstap的bug，有时候sstap会出问题，已每秒几十上百的速度疯狂发起连接。重启一下或者换一个版本再试。

也有可能是没配置对，tinyportmapper转发了sstap之后，tinyportmapper的流量又被sstap劫持了，造成了环路。 自己在sstap里加下路由例外。

**Comment by Cathgao** [comment]
请问路由例外要添加哪个地址？127.0.0.1不允许添加

**Comment by wangyu-** [comment]
添加VPS的ip地址和127.0.0.1

>127.0.0.1不允许添加

127.0.0.1应该是默认例外的，不加应该也行。

**Comment by Cathgao** [comment]
添加VPS服务器之后解决了。谢谢解答！大大的工具很好用

**Comment by Norswear** [comment]
请问：我的ssr设置的8000端口，那是不是用udp2raw转发ssr的8000端口的udp流量到4096端口，然后用tinyPortMapper转发ssr的同样是8000端口的tcp流量到同一端口（还是8000），这样对吗？

**Comment by qc5111** [comment]
你们最后规则是如何设置的？

**Comment by qc5111** [comment]
我的规则设置成：
13.54.63.252/32
13.56.63.251/32
13.58.0.253/32
13.112.63.251/32
13.124.63.251/32
13.126.0.252/32
13.228.0.251/32
23.23.255.255/32
34.192.0.54/32
34.208.63.251/32
34.224.0.252/32
34.248.60.213/32
35.154.63.252/32
35.156.63.252/32
35.157.61.4 /32
35.157.61.251 /32
35.160.63.253/32
35.176.0.252/32
35.182.0.251/32
46.51.178.50/32
46.51.216.14/32
46.51.255.254/32
46.137.120.1/32
46.137.191.254/32
46.137.255.254/32
50.17.255.254/32
50.18.56.1/32
50.19.255.254/32
50.112.120.53/32
52.1.255.254/32
52.2.0.2/32
52.7.255.255/32
52.8.191.254/32
52.9.63.252/32
52.10.63.252/32
52.13.255.255/32
52.14.64.0/32
52.15.55.0 /32
52.16.0.2/32
52.19.0.2/32
52.20.63.253/32
52.24.63.252/32
52.28.34.137 /32
52.28.63.252/32
52.29.63.252/32
52.29.125.80 /32
52.30.63.252/32
52.32.63.252/32
52.36.0.2/32
52.43.255.254/32
52.45.127.254/32
52.48.63.252/32
52.52.63.252/32
52.54.63.252/32
52.56.34.0 /32
52.57.67.93/32
52.57.168.131 /32
52.57.169.116 /32
52.57.241.171 /32
52.57.255.254/32
52.58.63.252/32
52.58.95.114 /32
52.59.68.3 /32
52.60.50.0/32
52.62.63.252/32
52.64.63.253/32
52.64.191.252/32
52.65.63.252/32
52.66.66.2/32
52.67.255.254/32
52.68.63.252/32
52.70.63.252/32
52.72.63.252/32
52.74.0.2/32
52.76.0.2/32
52.76.191.252/32
52.77.63.252/32
52.78.63.252/32
52.79.52.64/32
52.86.63.252/32
52.88.0.2/32
52.90.63.252/32
52.192.63.252/32
52.196.63.252/32
52.200.255.254/32
52.215.255.254/32
52.221.255.252/32
52.222.9.163 /32
54.64.0.2/32
54.66.0.2/32
54.66.191.252/32
54.67.63.253/32
54.68.63.252/32
54.70.0.12/32
54.72.255.252/32
54.73.0.1/32
54.74.0.1/32
54.76.0.3/32
54.78.0.3/32
54.79.127.252/32
54.80.0.2/32
54.84.0.3/32
54.86.63.252/32
54.88.0.3/32
54.89.0.3/32
54.90.0.3/32
54.92.0.2/32
54.92.128.2/32
54.93.32.2/32
54.93.162.162/32
54.94.0.66/32
54.94.191.252/32
54.95.0.2/32
54.144.0.2/32
54.148.0.2/32
54.150.0.255/32
54.151.0.2/32
54.151.128.2/32
54.152.63.252/32
54.153.63.252/32
54.153.191.252 /32
54.154.63.252/32
54.155.0.1/32
54.156.0.0/32
54.160.0.2/32
54.164.63.252/32
54.166.0.2/32
54.168.0.2/32
54.169.0.2/32
54.169.191.253/32
54.170.248.3/32
54.171.63.252/32
54.172.63.252/32
54.174.0.2/32
54.176.64.1/32
54.178.0.2/32
54.179.0.2/32
54.179.191.252/32
54.183.64.3/32
54.184.0.3/32
54.186.0.3/32
54.188.0.0/32
54.190.0.0/32
54.191.63.252/32
54.193.0.3/32
54.194.255.254/32
54.196.0.1/32
54.198.0.1/32
54.199.127.255/32
54.200.0.1/32
54.202.0.1/32
54.205.255.255/32
54.206.127.254 /32
54.206.128.2/32
54.207.127.254/32
54.208.0.1/32
54.210.63.252/32
54.212.0.0/32
54.214.0.1/32
54.215.0.1/32
54.216.0.1/32
54.218.4.254/32
54.219.127.255/32
54.220.0.0/32
54.221.214.221/32
54.225.110.215/32
54.226.0.1/32
54.228.250.251/32
54.229.0.1/32
54.232.127.254/32
54.233.127.252/32
54.233.192.0/32
54.235.236.60/32
54.236.0.0/32
54.238.0.0/32
54.240.0.0/32
54.240.8.0/32
54.240.16.0/32
54.240.24.0/32
54.240.49.254/32
54.240.56.254/32
54.240.63.254/32
54.241.127.255/32
54.243.255.254/32
54.244.128.1/32
54.245.127.255/32
54.246.127.255/32
54.247.127.254/32
54.248.127.254/32
54.250.128.0/32
54.251.63.255/32
54.252.88.8/32
54.253.0.1/32
54.254.128.1/32
54.255.0.2/32
67.202.0.5/32
72.44.32.8/32
75.101.163.105/32
79.125.120.9/32
103.4.10.139/32
107.22.255.255/32
122.248.255.254/32
174.129.0.31/32
175.41.146.190/32
175.41.248.202/32
176.32.95.254/32
176.34.56.254/32
176.34.127.254/32
176.34.255.255/32
177.71.255.255/32
184.72.56.36/32
184.72.92.4/32
184.72.255.254/32
184.73.173.231/32
184.169.255.254/32
185.48.120.66 /32
204.236.129.206/32
204.236.238.4/32
根本没有包含我自己的服务器和127.0.0.1 还是发生了回环

**Comment by qc5111** [comment]
好吧我会了谢谢！

**Comment by Cathgao** [comment]
> 好吧我会了谢谢！

是要在例外里面添加你的服务器地址，不然你的服务器地址会在代理ip里面，这样的逻辑就是你的服务器本身要被你的服务器所代理，这就有一个回路
